### ISSUE TITLE
Do'nt replacement response

### ISSUE THREAD

**Issue by hirocaster** [cloudspannerecosystem/pgadapter#5]
I tried `-j` option

replace.json
```
{
  "commands":
  [
    {
      "input_pattern": "^SELECT version();$",
      "output_pattern": "PostgreSQL 9.6.17 on x86_64-pc-linux-gnu, compiled by gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516, 64-bit",
      "matcher_array": []
    }
  ]
}

```

exec query by `psql` command.

```
example-db=> SELECT version();
ERROR:  INVALID_ARGUMENT: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Function not found: version [at 1:8]
SELECT version();
```

It seems that the query is sent as it is to the spanner.

**Comment by j-clap** [comment]
Hi hirocaster,

In order to use the JSON specification in psql mode, you must also toggle psql mode on. To do so, you need to also specify "-q" in the command line. Without it, the replacement rules are not toggled. I will try to make that more specific in the error message at a later iteration and more explicit in the README. Can you tell me if that works? If not it may be that you are not providing the full path for the JSON replacement file.

This should now be more explicit with the new PR: https://github.com/cloudspannerecosystem/pgadapter/pull/6

**Comment by hirocaster** [comment]
Thanks reply.

I try add `-q` option.

```
$ java -jar ./target/google-cloud-spanner-pgadapter-2.0.0-SNAPSHOT.jar -p my-project -i test-instance -d example-db -c /home/hirocaster/.config/xxxxxx.json -q -j /home/hirocaster/replacement.json
Apr 13, 2020 8:19:01 AM com.google.cloud.spanner.pgadapter.ProxyServer startServer
INFO: Server is starting on port 5,432
Apr 13, 2020 8:19:01 AM com.google.cloud.spanner.pgadapter.ProxyServer startServer
INFO: Server started on port 5,432
Apr 13, 2020 8:19:07 AM com.google.cloud.spanner.pgadapter.ConnectionHandler <init>
INFO: Connection handler with ID ConnectionHandler-1 created for client 127.0.0.1
Apr 13, 2020 8:19:07 AM com.google.cloud.spanner.pgadapter.ConnectionHandler run
INFO: Connection handler with ID ConnectionHandler-1 starting for client 127.0.0.1
Apr 13, 2020 8:19:07 AM com.google.cloud.spanner.pgadapter.ConnectionHandler run
INFO: Connection handler with ID ConnectionHandler-1 authenticated for client 127.0.0.1
```

use json file.
```json
{
  "commands":
  [
    {
      "input_pattern": "^SELECT version();$",
      "output_pattern": "PostgreSQL 9.6.17 on x86_64-pc-linux-gnu, compiled by gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516, 64-bit",
      "matcher_array": []
    },
    {
      "input_pattern": "^SELECT * FROM users;$",
      "output_pattern": "SELECT 1;",
      "matcher_array": []
    }
  ]
}
```

but, not replacement...

```shell
$ psql -h 127.0.0.1 -d example-db
psql (9.6.17, server 0.0.0)
Type "help" for help.

example-db=> SELECT * FROM users;
ERROR:  INVALID_ARGUMENT: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Table not found: users [at 1:15]
SELECT * FROM users;
              ^
example-db=> ^C
example-db=> ^C
example-db=> \q
```

**Comment by j-clap** [comment]
The issue in this case is that you need to escape some of the characters, since Java RegEx gives special meanings to parentheses (groups) and asterisks (0+ matches of the previous character). If you replace your strings with the following it should work (I tested it to make sure):

`"^SELECT version\\(\\);$"` (previously it was trying to catch an empty group)
`"^SELECT \\* FROM users;$"` (previously it was matching 0 or more spaces)

Note however that the output pattern replacement you made for the first pattern will fail as well. I would recommend wrapping it is quotes and prefacing it with `SELECT`.

Hope this helps :)
